### PR TITLE
Add Faker.Name.name/1

### PR DESCRIPTION
**Pull request by vbrazo**
I've added:

- [x] `CHANGELOG.md`
- [x] `Faker.Name.middle_name`
- [x] `Faker.Name.name_with_middle`
- [x] `Faker.Name.En.middle_name`
- [x] `Faker.Name.En.name_with_middle`

### CODE REVIEW

**Comment by igas** [comment]
API wise, what do you think about making `name/1` with attributes instead of a new method?

I think if we test just `name/0` we would get with or without a middle name. If we look at it from testing perspective, name if like the full name which is a single field, and people can enter with or without a middle name.

`name/0` => `name(with_middle_name: nil)`
`name(with_middle_name: nil)` => random `name(with_middle_name: true/false)`
`name(with_middle_name: true)`
`name(with_middle_name: false)`

**Comment by vbrazo** [comment]
I agree. I'll work on these changes next week. I'm travelling in the mountains in midwest Brazil.

**Comment by anthonator** [comment]
Since the `Faker.Name` API has been deprecated and this issue has gone stale I'm going to close this pull request. Feel free to open a new pull request with the required changes.

**Comment by vbrazo** [comment]
No problem! Thanks 👍

**Pull request closed without merging**
