### PR TITLE
Breaking Change: add Faker.Fiction namespace

### PR DESCRIPTION
**Pull request by igas**

### CODE REVIEW

**Comment by igas** [comment]
@vbrazo please take a look, what do you think?

**Comment by vbrazo** [comment]
@igas I think it's a great time to introduce this kind of namespaces since the library is still young. Defining good taxonomy will be always challenging and we're here to suggest names if needed.

Would we need to deprecate these old modules?

**Comment by igas** [comment]
@vbrazo agreed, I looked at different faker libs and what they suggested and so far this one I'm comfortable with, there are others I saw like Books, TvShows, Movies, PopCulture etc, but I think they are often mixed like Books/TvShows, so I guess Fiction would be a good one.

Regarding deprecations, this is the good question, we are pre 1.0, which means API is not stable, but I guess we still can make it right for our users. Wanna get on top of it?

**Comment by vbrazo** [comment]
sure, why not? We can add the namespaces together. 

Let me open a new issue to centralize the discussions there.

**Comment by anthonator** [comment]
This is stale so going to close.

**Pull request closed without merging**
