### PR TITLE
Fix: invalid bidirectional formatting

### PR DESCRIPTION
**Pull request by MichalDolata**
I've added:

- [ ] USAGE.md docs if applicable
- [x] CHANGELOG.md

In [Elixir v1.13](https://github.com/elixir-lang/elixir/blob/v1.13/CHANGELOG.md#2-bug-fixes) there will be checking for  bidirectional characters in strings and comments, because of that current version of master doesn't compile. This change will allow using Faker with v1.13+
image

### CODE REVIEW

**Review by anthonator — APPROVED** [review]

**Comment by MichalDolata** [comment]
@anthonator Hi, I've upgraded Credo to 1.6.0 because Elixir 1.13 doesn't work with older versions of Credo

**Comment by anthonator** [comment]
#435 and #436 should resolve the credo issues.

**Comment by anthonator** [comment]
Thanks for the contribution @MichalDolata!

**Comment by markomitranic** [comment]
@anthonator Awesome work! :) When an we expect a new release which includes this fix?

**Comment by anthonator** [comment]
@markomitranic please see https://github.com/elixirs/faker/issues/437#issuecomment-986346720

**Pull request merged**
