### PR TITLE
Add US Employer Identification Number

### PR DESCRIPTION
**Pull request by artkay**
I've added:

US [Employer Identification Number](https://en.wikipedia.org/wiki/Employer_Identification_Number) generator (kind of like SSN for businesses)

- [ ] USAGE.md docs if applicable
- [x] CHANGELOG.md

### CODE REVIEW

**Comment by artkay** [comment]
Hey @vbrazo - any chance this can be reviewed?
I think Travis failed to report success back - if you click on details it'll show the green.

**Comment by artkay** [comment]
Maybe @igas can take a look?

**Comment by anthonator** [comment]
Could you please add usage documentation?

**Comment by artkay** [comment]
> Could you please add usage documentation?

Hey @anthonator, I considered changing of `USAGE.md` is not applicable here because it [already contains the link](https://github.com/elixirs/faker/blame/master/USAGE.md#L48) to `Faker.Gov.Us` and thus no changes needed:

[I added the description with some examples to the module](https://github.com/elixirs/faker/pull/342/files#diff-253a255938ddd93f2890348828ede4caR35-R48) - is there anything else you would like me to add regarding the usage?

**Comment by anthonator** [comment]
Thanks for the contribution!

**Pull request merged**
